### ISSUE TITLE
[Improvement] Over the current of adding new datasets

### ISSUE THREAD

**Issue by asvskartheek** [jerinphilip/ilmulti#9]
The "code adaptation" for training the model on datasets and languages that aren't already present in the library is:

Present: 
Changing corpora.py in fairseq-ilmt this has been moved to [ilmulti](https://github.com/jerinphilip/ilmulti/blob/dev/ilmulti/registry/datasets.py) in [this commit](https://github.com/jerinphilip/ilmulti/commit/7269131e6e2273e0d74e31d0b0b88519803581e6) 

BUT 

Proposed: 
A. Can we change this to something like how fairseq handles user-defined tasks/models where we pass in a module containing user-defined "things"  like [this](https://github.com/pytorch/fairseq/blob/1c0439b7dabe62d39c6e7f1c8ebc86311e042b5a/fairseq/utils.py#L434) 
OR
B. Since already all the information except for the path is already present in the configuration file. We can add another path key in the datasets that gives the path to the dataset folder. If this route is taken, we have to ensure a standard format on data files.

Reason for this suggestion: Cleaner (Opinion), Doesn't have to change the library code i.e, becomes "plug and play" type approach.

**Comment by jerinphilip** [comment]
@asvskartheek I'm not sure I understand A. Is this a provision to add user specified tasks somewhere? I think we can't just settle for A (part of this is the cluster (ada), a lot of our problems will get solved with infinite RAM and storage :D).  

What I envision is that this library includes fairseq (as a vanilla dependency, I don't write inside and modify like I did with fairseq-ilmt). I upgrade fairseq, I only upgrade the wiring in here if anything has changed. It's really hard to do that when I've diverged fairseq editing in the other place. This place will register task and datasets into fairseq during runtime (it's a similar dict) and extra adjustments. Give a pseudo-cli which internally calls fairseq-*.  Does this sound like a cleaner solution for achieving the same?

In any case, the basic code we setup here for both (user module or wrapper) will be the same. So both of us should be happy. 

> If this route is taken, we have to ensure a standard format on data files.

My assumption is a data root set through environment and files having a relative path standard to it. That doesn't cover the use-case?

**Comment by asvskartheek** [comment]
A. True, Understood.
> this library includes fairseq (as a vanilla dependency

B. I am under the assumption that we'll be using fairseq-ilmt (which is very different from the 'latest commit' of fairseq) while making this suggestion. If we're using fairseq to train, this issue doesn't exist because all of this will get handled during the `fairseq-preprocess` call i.e, preprocessing and binarizing.

> My assumption is a data root set through environment and files having a relative path standard to it. That doesn't cover the use-case?

This is very close to standardization. I always liked the ILMULTI_CORPUS_ROOT env variable for the data root idea. I meant further standardization including the sub_path and corpus_name [like here](https://github.com/jerinphilip/ilmulti/blob/dev/ilmulti/registry/datasets.py#L76-L79). But on second thought, this might reduce the flexibility of the file naming and its paths.

**Comment by jerinphilip** [comment]
>  I am under the assumption that we'll be using fairseq-ilmt

I wrote that pretty naive when I wanted a stable thing to edit. 2 years down the line it's really hard to bring features from upstream and put it in fairseq-ilmt. The models trained with that doesn't even seem to be loading now with the new one. If It's just version bumps and keeping the task + fairseq adjustment code here, just writing a wrapper layer it might be easier to upgrade versions. Just find the faults here and fix, while fairseq can be expected to work and changes easily trackable. So the idea is this becomes a thin-wrapper which we fast iterate our experiments with our internal setup and cluster limitations.

**Comment by asvskartheek** [comment]
Got it.
